spring.application.name=server2-nhi
server.port=${PORT:8080}
spring.datasource.url=${DATABASE_URL}
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
server1.url=${SERVER1_URL:https://server1-ngan.onrender.com}
server3.url=${SERVER3_URL:https://server3-my.onrender.com}
station.name=Tram 2 - Nhi
station.id=server2-nhi
management.endpoints.web.exposure.include=health,info
