spring.application.name=server3-my
server.port=${PORT:8080}
spring.datasource.url=${DATABASE_URL}
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
server1.url=${SERVER1_URL:https://server1-ngan.onrender.com}
server4.url=${SERVER4_URL:https://server4-suong.onrender.com}
station.name=Tram 3 - My
station.id=server3-my
management.endpoints.web.exposure.include=health,info
