spring.application.name=server4-suong
server.port=${PORT:8080}

spring.datasource.url=${SPRING_DATASOURCE_URL}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false

server1.url=${SERVER1_URL:https://server1-ngan.onrender.com}
server5.url=${SERVER5_URL:https://server5-hang.onrender.com}

management.endpoints.web.exposure.include=health,info